services:

  app:
    build: .
    image: workshop-organizer
    container_name: workshop-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/workshopsdb"
      SPRING_DATASOURCE_USERNAME: workshops_user
      SPRING_DATASOURCE_PASSWORD: oc2024
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: workshops_user
      POSTGRES_PASSWORD: oc2024
      POSTGRES_DB: workshopsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistance des données
    healthcheck: # Vérification de santé (Demandé)
      test: ["CMD-SHELL", "pg_isready -U workshops_user -d workshopsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
